name = "resolvex-web"
main = ".output/server/index.mjs"
compatibility_date = "2023-08-13"

[site]
bucket = ".output/public"

[env.development]
route = { pattern = "development.resolvex.ai", custom_domain = true }
services = [{ binding = "API_SERVICE", service = "resolvex-api-development" }]

[env.preview]
route = { pattern = "preview.resolvex.ai", custom_domain = true }
services = [{ binding = "API_SERVICE", service = "resolvex-api-preview" }]

[env.production]
logpush = true
route = { pattern = "resolvex.ai", custom_domain = true }
services = [{ binding = "API_SERVICE", service = "resolvex-api-production" }]
