name = "test-web"
main = ".output/server/index.mjs"
compatibility_date = "2023-08-13"

[site]
bucket = ".output/public"

[env.development]
route = { pattern = "development.test.potensd.dev", custom_domain = true }
services = [{ binding = "API_SERVICE", service = "test-api-development" }]

[env.preview]
route = { pattern = "preview.test.potensd.dev", custom_domain = true }
services = [{ binding = "API_SERVICE", service = "test-api-preview" }]

[env.production]
logpush = true
route = { pattern = "test.potensd.dev", custom_domain = true }
services = [{ binding = "API_SERVICE", service = "test-api-production" }]
