name = "test-api"
main = "src/worker.ts"
compatibility_date = "2023-08-13"

[env.local]
vars = { WORKER_ENV = "development", WEB_URL = "http://localhost:3000" }
d1_databases = [
    { binding = "DB", database_name = "main-db", database_id = "0f11479b-c924-4a87-9e71-8a46d613840a" },
]

[env.development]
route = { pattern = "development.api.test.potensd.dev", custom_domain = true }
vars = { WORKER_ENV = "development", WEB_URL = "https://development.test.potensd.dev" }
d1_databases = [
    { binding = "DB", database_name = "main-db", database_id = "0f11479b-c924-4a87-9e71-8a46d613840a" },
]

[env.preview]
route = { pattern = "preview.api.test.potensd.dev", custom_domain = true }
vars = { WORKER_ENV = "development", WEB_URL = "https://preview.test.potensd.dev" }
d1_databases = [
    { binding = "DB", database_name = "main-db", database_id = "0f11479b-c924-4a87-9e71-8a46d613840a" },
]

[env.production]
logpush = true
route = { pattern = "api.test.potensd.dev", custom_domain = true }
vars = { WORKER_ENV = "production", WEB_URL = "https://test.potensd.dev" }
d1_databases = [
    { binding = "DB", database_name = "main-db", database_id = "0f11479b-c924-4a87-9e71-8a46d613840a" },
]
